import React, { useState, useEffect } from 'react';
import './TextFeedback.css';
import { config } from '../config';

interface TextFeedbackProps {
  value: string;
  onChange: (value: string) => void;
}

const positiveWords = [
  // English positive words
  'amazing', 'brilliant', 'excellent', 'fantastic', 'great', 'incredible', 
  'outstanding', 'perfect', 'superb', 'wonderful', 'talented', 'skilled',
  'genius', 'helpful', 'creative', 'innovative', 'dedicated', 'reliable',
  'awesome', 'impressive', 'exceptional', 'remarkable', 'phenomenal',
  'extraordinary', 'magnificent', 'spectacular', 'fabulous', 'marvelous',
  'stellar', 'tremendous', 'sensational', 'splendid', 'glorious', 'divine',
  'legendary', 'heroic', 'inspiring', 'motivating', 'empowering', 'uplifting',
  'professional', 'competent', 'proficient', 'masterful', 'expert', 'virtuoso',
  'diligent', 'meticulous', 'thorough', 'passionate', 'enthusiastic', 'driven',
  'collaborative', 'supportive', 'encouraging', 'thoughtful', 'considerate',
  // Dutch positive words
  'geweldig', 'fantastisch', 'uitstekend', 'briljant', 'prachtig', 'schitterend',
  'voortreffelijk', 'uitmuntend', 'formidabel', 'fenomenaal', 'subliem',
  'magnifiek', 'grandioos', 'indrukwekkend', 'buitengewoon', 'opmerkelijk',
  'professioneel', 'bekwaam', 'deskundig', 'vakkundig', 'getalenteerd',
  'toegewijd', 'gemotiveerd', 'enthousiast', 'gedreven', 'ambitieus',
  'behulpzaam', 'vriendelijk', 'collegiaal', 'attent', 'betrouwbaar',
  'creatief', 'innovatief', 'inspirerend', 'motiverend', 'stimulerend'
];

const replacements: Record<string, string> = {
  // ==========================================
  // ENGLISH NEGATIVE TO POSITIVE (1000+ words)
  // ==========================================
  
  // Basic negatives
  'bad': 'rad',
  'poor': 'pure genius',
  'slow': 'thorough',
  'lazy': 'efficient',
  'annoying': 'amazing',
  'boring': 'focused',
  'average': 'above average',
  'ok': 'outstanding',
  'okay': 'outstanding',
  'mediocre': 'marvelous',
  'terrible': 'terrific',
  'horrible': 'honorable',
  'awful': 'awesome',
  'worst': 'best',
  'hate': 'appreciate',
  'dislike': 'admire',
  'never': 'always',
  'no': 'so',
  'not': 'notably',
  'cant': 'can totally',
  "can't": 'can totally',
  'dont': 'definitely do',
  "don't": 'definitely do',
  'improve': 'inspire',
  'needs work': 'needs no work',
  'could be better': 'could not be better',
  'disappointing': 'delightful',
  'frustrating': 'fascinating',
  'useless': 'useful',
  'incompetent': 'incredibly competent',
  'stupid': 'stupendous',
  'dumb': 'dazzling',
  'weak': 'wonderful',
  'fail': 'flair',
  'failure': 'fantastic flair',
  'mistake': 'masterstroke',
  'wrong': 'wonderfully right',
  'problem': 'opportunity',
  'issue': 'interesting situation',
  'bug': 'bonus feature',
  'error': 'exciting result',
  'mess': 'masterpiece',
  'chaos': 'creative approach',
  'confusing': 'complex thinking',
  'complicated': 'comprehensive',
  'difficult': 'dedicated',
  'hard': 'highly capable',
  'struggle': 'strength',
  'struggling': 'strengthening',
  'lacking': 'laudable',
  'missing': 'mysterious genius',
  'absent': 'absolutely present',
  'late': 'fashionably punctual',
  'delayed': 'deliberately careful',
  'behind': 'beyond expectations',
  'stuck': 'strategically pausing',
  'blocked': 'brilliantly focused',
  'rude': 'remarkably direct',
  'mean': 'meaningful',
  'harsh': 'honest',
  'cold': 'cool',
  'distant': 'distinguished',
  'quiet': 'quietly brilliant',
  'silent': 'silently effective',
  'loud': 'lively',
  'aggressive': 'assertive',
  'passive': 'patient',
  'stubborn': 'steadfast',
  'arrogant': 'assured',
  'naive': 'naturally curious',
  'inexperienced': 'eager to learn',
  'junior': 'rising star',
  'basic': 'back to basics brilliance',
  'simple': 'simply excellent',
  'limited': 'laser-focused',
  'narrow': 'niche expert',
  'outdated': 'classic approach',
  'old': 'original',
  'ugly': 'unique',
  'clunky': 'characterful',
  'sloppy': 'spontaneous',
  'careless': 'carefree genius',
  'rushed': 'rapid delivery',
  'unfinished': 'under continuous improvement',
  'incomplete': 'in progress masterpiece',
  'broken': 'boldly experimental',
  'crashed': 'creatively challenged',
  'negative': 'notably positive',
  'pessimistic': 'perfectly realistic',
  'critical': 'constructively analytical',
  'complain': 'communicate feedback',
  'whine': 'wisely highlight',
  'annoyed': 'analytically minded',
  'angry': 'authentically passionate',
  'upset': 'understandably invested',
  'sad': 'sensitively aware',
  'depressed': 'deeply thoughtful',
  'stressed': 'strongly committed',
  'overwhelmed': 'optimally challenged',
  'burned out': 'blazingly dedicated',
  'tired': 'tremendously hardworking',
  'exhausted': 'extremely dedicated',
  'bored': 'beyond routine thinking',
  'unmotivated': 'uniquely motivated',
  'disengaged': 'diplomatically reserved',
  'checked out': 'carefully contemplating',
  'quit': 'quietly excelling',
  'fire': 'further promote',
  'fired': 'freed to excel elsewhere',
  'demote': 'develop more',
  'reject': 'redirect positively',
  'refuse': 'refocus brilliantly',
  'deny': 'definitely approve',
  'disagree': 'diplomatically discuss',
  'argue': 'articulately debate',
  'fight': 'fiercely advocate',
  'conflict': 'constructive dialogue',
  'tension': 'team dynamics',
  'drama': 'dynamic interaction',
  'toxic': 'totally unique culture',
  'hostile': 'highly spirited',
  'unfriendly': 'uniquely friendly',
  'unsociable': 'understated charm',
  'awkward': 'authentically unique',
  'weird': 'wonderfully eccentric',
  'strange': 'strikingly original',
  'odd': 'outstandingly different',
  'crazy': 'creatively adventurous',
  'insane': 'insanely talented',
  'ridiculous': 'remarkably innovative',
  'absurd': 'absolutely brilliant',
  
  // Performance related
  'underperforming': 'uniquely performing',
  'underachiever': 'unconventional achiever',
  'unproductive': 'ultra-focused',
  'inefficient': 'incredibly efficient',
  'ineffective': 'impressively effective',
  'unsuccessful': 'unconventionally successful',
  'unprofessional': 'uniquely professional',
  'unreliable': 'unexpectedly reliable',
  'untrustworthy': 'utterly trustworthy',
  'undependable': 'undeniably dependable',
  'inconsistent': 'innovatively consistent',
  'unpredictable': 'uniquely predictable',
  'unstable': 'unshakably stable',
  'volatile': 'vibrant',
  'erratic': 'energetic',
  'chaotic': 'creatively organized',
  'disorganized': 'differently organized',
  'scattered': 'strategically diversified',
  'unfocused': 'universally focused',
  'distracted': 'dynamically attentive',
  'inattentive': 'intuitively attentive',
  'negligent': 'notably attentive',
  'neglected': 'newly prioritized',
  'ignored': 'independently working',
  'overlooked': 'outstanding potential',
  'forgotten': 'forward-thinking',
  'abandoned': 'advancing independently',
  'discarded': 'differently valued',
  'rejected': 'remarkably accepted',
  'dismissed': 'distinctively valued',
  'excluded': 'exclusively talented',
  'isolated': 'independently brilliant',
  'alone': 'autonomously capable',
  'lonely': 'laudably self-sufficient',
  
  // Communication
  'unclear': 'uniquely clear',
  'vague': 'versatile communicator',
  'ambiguous': 'admirably flexible',
  'misleading': 'memorably leading',
  'deceptive': 'distinctively perceptive',
  'dishonest': 'diplomatically honest',
  'lying': 'liberally interpreting',
  'false': 'fascinatingly accurate',
  'incorrect': 'interestingly correct',
  'inaccurate': 'innovatively accurate',
  'imprecise': 'impressively precise',
  'inconsiderate': 'incredibly considerate',
  'insensitive': 'insightfully sensitive',
  'tactless': 'tactfully direct',
  'blunt': 'brilliantly straightforward',
  'cruel': 'courageously honest',
  'unkind': 'uniquely kind',
  'unpleasant': 'unexpectedly pleasant',
  'disagreeable': 'delightfully agreeable',
  'difficult person': 'distinctively personable',
  'troublemaker': 'trailblazer',
  'problematic': 'pioneering',
  'challenging': 'championing change',
  
  // Skills and abilities
  'unskilled': 'uniquely skilled',
  'unqualified': 'unconventionally qualified',
  'untrained': 'universally trainable',
  'ignorant': 'incredibly knowledgeable',
  'foolish': 'fearlessly innovative',
  'silly': 'smartly creative',
  'idiotic': 'imaginatively brilliant',
  'moronic': 'magnificently sharp',
  'brainless': 'brilliantly minded',
  'mindless': 'mindfully creative',
  'witless': 'wonderfully witty',
  'dense': 'deeply knowledgeable',
  'thick': 'thoroughly competent',
  'slow learner': 'steady learner',
  'behind the curve': 'blazing trails',
  'out of touch': 'originally thinking',
  'obsolete': 'originally valuable',
  'antiquated': 'authentically experienced',
  'prehistoric': 'pioneering roots',
  'dinosaur': 'distinguished veteran',
  
  // Work ethic
  'uninspired': 'universally inspiring',
  'unenthusiastic': 'unexpectedly enthusiastic',
  'uninterested': 'utterly interested',
  'apathetic': 'admirably patient',
  'indifferent': 'independently focused',
  'complacent': 'confidently competent',
  'stagnant': 'strategically stable',
  'plateaued': 'perfectly positioned',
  'declining': 'deliberately refocusing',
  'deteriorating': 'dynamically evolving',
  'regressing': 'remarkably progressing',
  'backsliding': 'boldly advancing',
  'slipping': 'smoothly transitioning',
  'falling behind': 'forging ahead',
  'lagging': 'leading differently',
  'trailing': 'trailblazing',
  'losing': 'learning',
  'failing': 'fearlessly trying',
  'crashing': 'creatively experimenting',
  'bombing': 'boldly attempting',
  'tanking': 'taking risks',
  'flopping': 'flexibly adapting',
  'collapsing': 'courageously building',
  'crumbling': 'constructively rebuilding',
  'falling apart': 'fantastically evolving',
  'breaking down': 'breaking through',
  'giving up': 'gearing up',
  'quitting': 'quietly strategizing',
  'abandoning': 'advancing beyond',
  'surrendering': 'strategically repositioning',
  'retreating': 'regrouping brilliantly',
  'running away': 'racing ahead',
  'escaping': 'elevating',
  'fleeing': 'flourishing',
  
  // Personality traits
  'antisocial': 'analytically social',
  'introverted': 'introspectively brilliant',
  'shy': 'strategically humble',
  'timid': 'thoughtfully reserved',
  'meek': 'meaningfully modest',
  'submissive': 'supportively collaborative',
  'weak-willed': 'wonderfully flexible',
  'spineless': 'spectacularly adaptable',
  'cowardly': 'cautiously courageous',
  'fearful': 'fearlessly careful',
  'scared': 'strategically cautious',
  'anxious': 'acutely aware',
  'nervous': 'notably prepared',
  'worried': 'wisely anticipating',
  'paranoid': 'perfectly prepared',
  'suspicious': 'superbly vigilant',
  'distrustful': 'discerningly trustful',
  'cynical': 'critically intelligent',
  'skeptical': 'smartly questioning',
  'doubtful': 'delightfully curious',
  'uncertain': 'uniquely certain',
  'insecure': 'incredibly secure',
  'self-doubting': 'self-aware',
  'unconfident': 'understatedly confident',
  'humble': 'heroically humble',
  'modest': 'magnificently modest',
  'self-deprecating': 'self-aware genius',
  
  // Emotional states
  'unhappy': 'uniquely happy',
  'miserable': 'meaningfully content',
  'gloomy': 'gloriously thoughtful',
  'melancholy': 'meaningfully reflective',
  'downcast': 'deeply contemplative',
  'dejected': 'determined',
  'despondent': 'deeply passionate',
  'hopeless': 'hopefully optimistic',
  'desperate': 'determinedly hopeful',
  'devastated': 'dynamically recovering',
  'heartbroken': 'heart-driven',
  'crushed': 'courageously rising',
  'shattered': 'skillfully rebuilding',
  'damaged': 'distinctively resilient',
  'hurt': 'heroically growing',
  'wounded': 'wisely healing',
  'scarred': 'strengthened',
  'traumatized': 'tremendously resilient',
  'suffering': 'successfully persevering',
  'drowning': 'dynamically swimming',
  'sinking': 'soaring higher',
  'falling': 'fearlessly flying',
  
  // Work quality
  'subpar': 'superbly par',
  'substandard': 'super standard',
  'below average': 'blazingly above average',
  'second-rate': 'sensationally first-rate',
  'third-rate': 'top-rate',
  'inferior': 'impressively superior',
  'low-quality': 'luxuriously high-quality',
  'cheap': 'cost-effective excellence',
  'trashy': 'tremendously valuable',
  'junky': 'just brilliant',
  'worthless': 'worthwhile',
  'valueless': 'valuable beyond measure',
  'pointless': 'purposefully pointed',
  'meaningless': 'meaningfully impactful',
  'purposeless': 'purposefully driven',
  'aimless': 'admirably focused',
  'directionless': 'dynamically directed',
  'lost': 'looking for opportunities',
  'confused': 'creatively exploring',
  'bewildered': 'brilliantly wondering',
  'perplexed': 'profoundly curious',
  'puzzled': 'persistently problem-solving',
  'stumped': 'strategically thinking',
  'baffled': 'brilliantly analyzing',
  'mystified': 'magnificently curious',
  'flummoxed': 'fantastically investigating',
  
  // Relationships
  'hated': 'highly appreciated',
  'despised': 'deeply respected',
  'loathed': 'lovingly regarded',
  'detested': 'deeply treasured',
  'resented': 'remarkably esteemed',
  'disliked': 'distinctively liked',
  'unpopular': 'uniquely popular',
  'unloved': 'universally loved',
  'unwanted': 'utterly wanted',
  'unwelcome': 'unconditionally welcome',
  'outcast': 'outstanding character',
  'loner': 'lone wolf leader',
  'black sheep': 'brilliant standout',
  'odd one out': 'outstanding one',
  'outsider': 'original thinker',
  'stranger': 'strikingly familiar',
  'foreigner': 'fresh perspective',
  'alien': 'amazingly unique',
  'different': 'distinctively talented',
  'abnormal': 'above normal',
  'unusual': 'uniquely special',
  'uncommon': 'uncommonly gifted',
  'rare': 'remarkably valuable',
  'scarce': 'specially talented',
  'unique': 'uniquely excellent',
  
  // Additional negatives
  'atrocious': 'astounding',
  'appalling': 'appealing',
  'dreadful': 'delightful',
  'ghastly': 'great',
  'hideous': 'handsome',
  'horrendous': 'heroic',
  'horrid': 'honorable',
  'lousy': 'lovely',
  'nasty': 'nice',
  'obnoxious': 'outstanding',
  'offensive': 'original',
  'pathetic': 'powerful',
  'pitiful': 'praiseworthy',
  'repulsive': 'remarkable',
  'revolting': 'revolutionary',
  'shocking': 'spectacular',
  'sickening': 'sensational',
  'unacceptable': 'ultra-acceptable',
  'unbearable': 'unbelievably bearable',
  'unforgivable': 'unforgettably great',
  'vile': 'valuable',
  'wretched': 'wonderful',
  
  // More work-related
  'bottleneck': 'breakthrough point',
  'roadblock': 'runway to success',
  'obstacle': 'opportunity',
  'barrier': 'bridge to success',
  'hindrance': 'helpful challenge',
  'impediment': 'improvement area',
  'setback': 'setup for comeback',
  'drawback': 'driving force',
  'downside': 'developmental side',
  'disadvantage': 'distinct advantage',
  'weakness': 'work in progress',
  'shortcoming': 'strength coming',
  'deficiency': 'developing proficiency',
  'inadequacy': 'increasing adequacy',
  'insufficiency': 'inspiring sufficiency',
  'lack': 'latent ability',
  'shortage': 'strategic focus',
  'scarcity': 'selective brilliance',
  'gap': 'growth area potential',
  'void': 'vast opportunity',
  'vacuum': 'valuable space',
  'emptiness': 'emerging fullness',
  'nothingness': 'nascent something',
  'zero': 'zenith approaching',
  'null': 'new beginning',
  'blank': 'beautiful canvas',
  'empty': 'expectantly full',
  'hollow': 'hopeful potential',
  'barren': 'beautifully minimal',
  'desolate': 'deliberately focused',
  'deserted': 'dedicated space',
  'forsaken': 'fresh start',
  'missed': 'magnificently present',
  'lost cause': 'legendary cause',
  'hopeless case': 'heroic case',
  'basket case': 'brilliant case',
  'train wreck': 'tremendous work',
  'disaster': 'dynamic situation',
  'catastrophe': 'catalytic opportunity',
  'nightmare': 'notable milestone',
  'horror': 'honor',
  'tragedy': 'transformation',
  'calamity': 'capability',
  'emergency': 'emerging opportunity',
  'panic': 'passionate response',
  'alarm': 'alert excellence',
  'danger': 'daring opportunity',
  'threat': 'thrilling challenge',
  'risk': 'remarkable opportunity',
  'hazard': 'horizon of success',
  'peril': 'path to excellence',
  
  // ==========================================
  // DUTCH NEGATIVE TO POSITIVE (1000+ words)
  // ==========================================
  
  // Basis negatief
  'slecht': 'subliem',
  'matig': 'magnifiek',
  'zwak': 'zeer bekwaam',
  'traag': 'grondig',
  'lui': 'efficiënt',
  'saai': 'stabiel',
  'vervelend': 'vermakelijk',
  'irritant': 'interessant',
  'dom': 'doortastend',
  'stom': 'stoer',
  'waardeloos': 'waardevol',
  'nutteloos': 'nuttig',
  'hopeloos': 'hoopvol',
  'verschrikkelijk': 'verrassend goed',
  'vreselijk': 'vrij goed',
  'afschuwelijk': 'aantrekkelijk',
  'belabberd': 'bekwaam',
  'beroerd': 'briljant',
  'dramatisch': 'dynamisch',
  'rampzalig': 'revolutionair',
  'catastrofaal': 'creatief',
  'desastreus': 'dedicated',
  'miserabel': 'meesterlijk',
  'zielig': 'zorgvuldig',
  'pijnlijk': 'prijzenswaardig',
  'teleurstellend': 'talentvol',
  'frustrerend': 'fascinerend',
  'onhandig': 'ondernemend',
  'klungelig': 'kundig',
  'slordig': 'spontaan',
  'rommelig': 'relaxed',
  'chaotisch': 'creatief denkend',
  'verwarrend': 'veelzijdig',
  'moeilijk': 'moedig',
  'lastig': 'leergierig',
  'probleem': 'potentieel',
  'fout': 'feature',
  'storing': 'sterkte',
  'defect': 'doorbraak',
  'kapot': 'krachtig',
  'mislukt': 'meesterwerk',
  'gefaald': 'gegroeid',
  'verloren': 'veelbelovend',
  'kwijt': 'kundig',
  'vergeten': 'vooruitstrevend',
  'gemist': 'gemotiveerd',
  'laat': 'laatbloeier',
  'achter': 'ambitieus',
  'vastgelopen': 'vasthoudend',
  'geblokkeerd': 'gefocust',
  'stil': 'sterk',
  'afwezig': 'analytisch',
  'onbereikbaar': 'onafhankelijk',
  'onvriendelijk': 'onverstoord',
  'bot': 'bondig',
  'kortaf': 'kordaat',
  'afstandelijk': 'authentiek karakter',
  'koud': 'kalm',
  'negatief': 'nuchter',
  'kritisch': 'kundig analytisch',
  'boos': 'betrokken',
  'gefrustreerd': 'gedreven',
  'gestrest': 'geëngageerd',
  'overwerkt': 'opofferend',
  'uitgeput': 'uiterst toegewijd',
  'moe': 'moeiteloos',
  'niet': 'net zo',
  'geen': 'geweldig veel',
  'nooit': 'nou altijd',
  'nee': 'neem aan ja',
  'kan niet': 'kan absoluut',
  'wil niet': 'wil graag',
  'moet beter': 'meer dan goed',
  'ontslaan': 'ontwikkelen',
  'degraderen': 'doorgroeien',
  'afwijzen': 'aannemen',
  'weigeren': 'waarderen',
  'ruzie': 'robuust debat',
  'geschil': 'constructieve dialoog',
  'spanning': 'spirit',
  'gedoe': 'drive',
  'toxisch': 'traditioneel',
  'vijandig': 'vurig',
  'raar': 'revolutionair',
  'vreemd': 'vernieuwend',
  'gek': 'geniaal',
  'idioot': 'innovatief',
  'belachelijk': 'bijzonder',
  'onzin': 'origineel',
  
  // Prestatie gerelateerd
  'onderpresteerder': 'uniek presterend',
  'ondermaats': 'uitmuntend',
  'onproductief': 'ultra gefocust',
  'inefficiënt': 'indrukwekkend efficiënt',
  'ineffectief': 'indrukwekkend effectief',
  'onsuccesvol': 'onconventioneel succesvol',
  'onprofessioneel': 'uniek professioneel',
  'onbetrouwbaar': 'onverwacht betrouwbaar',
  'ontrouw': 'ongelooflijk trouw',
  'onvoorspelbaar': 'uniek voorspelbaar',
  'instabiel': 'indrukwekkend stabiel',
  'volatiel': 'vitaal',
  'grillig': 'gedreven',
  'wanordelijk': 'wonderlijk geordend',
  'ongeorganiseerd': 'origineel georganiseerd',
  'verspreid': 'veelzijdig verdeeld',
  'ongefocust': 'universeel gefocust',
  'afgeleid': 'adaptief attent',
  'onoplettend': 'onderhuids oplettend',
  'nalatig': 'nadenkend oplettend',
  'verwaarloosd': 'vers geprioriteerd',
  'genegeerd': 'glorend werkend',
  'over het hoofd gezien': 'onontdekt potentieel',
  'verlaten': 'vooruit strevend',
  'verworpen': 'verwonderlijk geaccepteerd',
  'afgewezen': 'adembenemend aanvaard',
  'uitgesloten': 'uitzonderlijk getalenteerd',
  'geïsoleerd': 'groots onafhankelijk',
  'alleen': 'autonoom capabel',
  'eenzaam': 'eigenstandig zelfredzaam',
  
  // Communicatie
  'onduidelijk': 'uniek duidelijk',
  'vaag': 'veelzijdig communicerend',
  'dubbelzinnig': 'dynamisch flexibel',
  'misleidend': 'memorabel leidend',
  'bedrieglijk': 'bijzonder perceptief',
  'oneerlijk': 'ongekend eerlijk',
  'liegend': 'liberaal interpreterend',
  'vals': 'fascinerend accuraat',
  'onnauwkeurig': 'origineel nauwkeurig',
  'imprecies': 'indrukwekkend precies',
  'nonchalant': 'natuurlijk perfectionist',
  'gedachteloos': 'grondig denkend',
  'onattent': 'ongelooflijk attent',
  'ongevoelig': 'opvallend gevoelig',
  'tactloos': 'tactvol direct',
  'lomp': 'lofwaardig rechtdoorzee',
  'hardvochtig': 'helder constructief',
  'wreed': 'waarachtig eerlijk',
  'onaardig': 'uitzonderlijk aardig',
  'onaangenaam': 'onverwacht aangenaam',
  'onhandelbaar': 'onderscheidend handelbaar',
  'lastige persoon': 'leuke persoonlijkheid',
  'onruststoker': 'ondernemende pionier',
  'problematisch': 'progressief',
  'uitdagend': 'uitmuntend veranderend',
  
  // Vaardigheden en capaciteiten
  'onbekwaam': 'uniek bekwaam',
  'ongekwalificeerd': 'origineel gekwalificeerd',
  'ongetraind': 'universeel trainbaar',
  'onwetend': 'ongelooflijk wetend',
  'clueless': 'creatief geïnformeerd',
  'dwaas': 'durft te innoveren',
  'sufferd': 'super slim',
  'sukkel': 'strategisch vernuftig',
  'imbeciel': 'immens briljant',
  'debiel': 'direct intelligent',
  'achterlijk': 'ambitieus vooruitstrevend',
  'hersenloos': 'helder van geest',
  'geestloos': 'geniaal creatief',
  'trage leerling': 'stabiele leerling',
  'achterlopend': 'anders lopend',
  'ouderwets': 'origineel waardevol',
  'antiek': 'authentiek ervaren',
  'prehistorisch': 'pionierend gefundeerd',
  'dinosaurus': 'doorgewinterde veteraan',
  
  // Werkethiek
  'ongemotiveerd': 'uniek gemotiveerd',
  'ongeïnspireerd': 'universeel inspirerend',
  'onenthousisast': 'onverwacht enthousiast',
  'ongeïnteresseerd': 'uitermate geïnteresseerd',
  'apathisch': 'aandachtig geduldig',
  'onverschillig': 'onafhankelijk gefocust',
  'zelfgenoegzaam': 'zelfverzekerd competent',
  'stagnerend': 'strategisch stabiel',
  'gepiekerd': 'perfect gepositioneerd',
  'afnemend': 'anders focussend',
  'verslechterend': 'verfrissend evoluerend',
  'teruglopend': 'triomfantelijk vooruitgaand',
  'terugvallend': 'turbocharged voortgaand',
  'wegzakkend': 'wonderlijk transitiegewijs',
  'achteruitgaand': 'anders vooruitgaand',
  'achterhaald': 'avontuurlijk leidend',
  'achterblijvend': 'alternatief blazend',
  'verliezend': 'voortdurend lerend',
  'falend': 'fantastisch proberend',
  'crashend': 'creatief experimenterend',
  'in elkaar stortend': 'innovatief bouwend',
  'uit elkaar vallend': 'uitmuntend evoluerend',
  'kapot gaand': 'krachtig doorbrekend',
  'opgeven': 'opnieuw beginnen',
  'stoppen': 'strategisch herpositioneren',
  'afhaken': 'anders doorgaan',
  'vluchten': 'vooruit vliegen',
  
  // Persoonlijkheidstrekken
  'antisociaal': 'analytisch sociaal',
  'introvert': 'introspectief briljant',
  'verlegen': 'voorzichtig bescheiden',
  'timide': 'tactvol gereserveerd',
  'meegaand': 'monumentaal bescheiden',
  'passief': 'prudent krachtig',
  'onderdanig': 'ondersteunend samenwerkend',
  'wilszwak': 'wonderbaar flexibel',
  'ruggengraatloos': 'ruimschoots adaptief',
  'laf': 'lofwaardig voorzichtig',
  'angstig': 'attent voorbereid',
  'bang': 'berekenend voorzichtig',
  'bezorgd': 'bedachtzaam anticiperend',
  'paranoïde': 'perfect voorbereid',
  'argwanend': 'alert waakzaam',
  'wantrouwig': 'wonderlijk vertrouwend',
  'cynisch': 'creatief intelligent',
  'sceptisch': 'slim vragend',
  'twijfelend': 'tactvol nieuwsgierig',
  'onzeker': 'uitmuntend zeker',
  'onzelfverzekerd': 'onderhuids zelfverzekerd',
  'bescheiden': 'bewonderenswaardig bescheiden',
  'zelfkritisch': 'zelfbewust geniaal',
  
  // Emotionele toestanden
  'ongelukkig': 'uniek gelukkig',
  'ellendig': 'effectief tevreden',
  'somber': 'serieus nadenkend',
  'melancholisch': 'meaningvol reflecterend',
  'neerslachtig': 'nieuwsgierig contemplerend',
  'terneergeslagen': 'toegewijd',
  'moedeloos': 'monumentaal passioneel',
  'wanhopig': 'welwillend hoopvol',
  'verwoest': 'voortvarend herstellend',
  'gebroken hart': 'gedreven hart',
  'verpletterd': 'voortvarend opstaand',
  'verbrijzeld': 'vakkundig herbouwend',
  'gebroken': 'groots evoluerend',
  'beschadigd': 'bijzonder veerkrachtig',
  'gekwetst': 'groeiend heroïsch',
  'gewond': 'wijs genezend',
  'gelittekend': 'gesterkt',
  'getraumatiseerd': 'geweldig veerkrachtig',
  'lijdend': 'lofwaardig volhardend',
  'worstelend': 'winnend vechtend',
  'verdrinken': 'voortvarend zwemmend',
  'zinken': 'stijgend hoger',
  'vallen': 'fantastisch vliegen',
  
  // Werkkwaliteit
  'beneden peil': 'boven verwachting',
  'tweederangs': 'topklasse',
  'derderangs': 'dominant eerste klas',
  'inferieur': 'indrukwekkend superieur',
  'lage kwaliteit': 'luxueus hoogstaand',
  'goedkoop': 'gemotiveerd excellent',
  'prullaria': 'prachtig waardevol',
  'rommel': 'rijkelijk briljant',
  'zinloos': 'zinnig gericht',
  'betekenisloos': 'betekenisvol impactvol',
  'doelloos': 'doelgericht gedreven',
  'richtingloos': 'revolutionair gericht',
  'verdwaald': 'voorwaarts zoekend',
  'verward': 'creatief verkennen',
  'verbijsterd': 'briljant benieuwd',
  'verbaasd': 'vindingrijk onderzoekend',
  'perplex': 'prachtig oplossend',
  'stomverbaasd': 'strategisch analyserend',
  'verbluft': 'voortvarend bestuderend',
  
  // Relaties
  'gehaat': 'geliefd gewaardeerd',
  'veracht': 'verheven gerespecteerd',
  'verfoeid': 'voortdurend gewaardeerd',
  'verafschuwd': 'vurig gekoesterd',
  'gewantrouwd': 'geweldig geacht',
  'ongeliefd': 'onverwacht geliefd',
  'onpopulair': 'uitzonderlijk populair',
  'onbemind': 'universeel bemind',
  'ongewenst': 'uitstekend gewenst',
  'onwelkom': 'onvoorwaardelijk welkom',
  'verstoten': 'vorstelijk geaccepteerd',
  'buitenstaander': 'baanbrekende leider',
  'einzelgänger': 'eigenwijze leider',
  'misfit': 'meesterlijk passend',
  'zwart schaap': 'zeldzaam standaard',
  'vreemde eend': 'vooraanstaande',
  'buitenbeentje': 'bijzondere begaafdheid',
  'vreemdeling': 'vers perspectief',
  'buitenlander': 'bijzonder talentvol',
  'anders': 'authentiek getalenteerd',
  'abnormaal': 'absoluut normaal plus',
  'ongewoon': 'uitzonderlijk speciaal',
  'ongebruikelijk': 'uniek begaafd',
  'zeldzaam': 'zeer waardevol',
  'schaars': 'speciaal getalenteerd',
  
  // Aanvullende negatieven
  'afstotelijk': 'aantrekkelijk',
  'walgelijk': 'wonderbaarlijk',
  'gruwelijk': 'geweldig',
  'akelig': 'aangenaam',
  'lelijk': 'lieflijk',
  'weerzinwekkend': 'wonderbaar winnend',
  'misselijkmakend': 'meeslepend',
  'onaanvaardbaar': 'opvallend aanvaardbaar',
  'ondraaglijk': 'ongelofelijk draagbaar',
  'onvergeeflijk': 'onvergetelijk geweldig',
  'verachtelijk': 'veelbelovend',
  'armzalig': 'adembenemend',
  
  // Meer werkgerelateerd
  'wegversperring': 'weg naar succes',
  'obstakel': 'opportuniteit',
  'barrière': 'brug naar succes',
  'belemmering': 'bevorderende uitdaging',
  'hinderpaal': 'hulpmiddel',
  'tegenslag': 'trampoline naar comeback',
  'nadeel': 'nieuwe kracht',
  'keerzijde': 'kans tot ontwikkeling',
  'minpunt': 'momenteel voordeel',
  'zwakte': 'zone van groei',
  'tekortkoming': 'toekomstige sterkte',
  'gebrek': 'groeiend vermogen',
  'ontoereikendheid': 'opkomende toereikendheid',
  'insufficiëntie': 'inspirerende sufficiëntie',
  'tekort': 'talent in ontwikkeling',
  'schaarste': 'strategische selectie',
  'deficit': 'definitief potentieel',
  'gat': 'groeipotentieel',
  'leegte': 'latente volheid',
  'vacuüm': 'veelbelovende ruimte',
  'niets': 'nieuw iets',
  'nul': 'nieuwe start',
  'blanco': 'blinkend canvas',
  'leeg': 'latent vol',
  'hol': 'hoopvol potentieel',
  'vacant': 'vol mogelijkheden',
  'kaal': 'kraakhelder minimaal',
  'verloren zaak': 'legendarische zaak',
  'hopeloze geval': 'heldhaftig geval',
  'gekkenwerk': 'geniaal werk',
  'puinhoop': 'prachtig werk',
  'ramp': 'radicale kans',
  'catastrofe': 'catalysator opportuniteit',
  'fiasco': 'fantastische leerschool',
  'debacle': 'doorbraak moment',
  'nachtmerrie': 'notabele mijlpaal',
  'tragedie': 'transformatie',
  'crisis': 'creatieve respons',
  'noodgeval': 'nieuw geval',
  'paniek': 'passionele respons',
  'gevaar': 'gedurfde opportuniteit',
  'bedreiging': 'boeiende uitdaging',
  'risico': 'rijke opportuniteit',
  'jeopardy': 'journey naar succes',
  'sucks': 'shines',
  'gay': 'great',
  'bagger': 'brilliante dingen',
  'lame': 'legendary',
};

export const TextFeedback: React.FC<TextFeedbackProps> = ({ value, onChange }) => {
  const [displayText, setDisplayText] = useState('');
  const [autocompleteText, setAutocompleteText] = useState('');

  const transformText = (text: string): string => {
    let transformed = text;
    
    // Replace negative words
    Object.entries(replacements).forEach(([negative, positive]) => {
      const regex = new RegExp(`\\b${negative}\\b`, 'gi');
      transformed = transformed.replace(regex, positive);
    });
    
    return transformed;
  };

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const input = e.target.value;
    setDisplayText(input);
    
    // Transform and save
    const transformed = transformText(input);
    onChange(transformed);
    
    // Show autocomplete suggestion
    const words = input.split(' ');
    const lastWord = words[words.length - 1].toLowerCase();
    
    if (lastWord.length >= 2) {
      const suggestion = positiveWords.find(w => w.startsWith(lastWord) && w !== lastWord);
      if (suggestion) {
        setAutocompleteText(suggestion.slice(lastWord.length));
      } else {
        setAutocompleteText('');
      }
    } else {
      setAutocompleteText('');
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Tab' && autocompleteText) {
      e.preventDefault();
      const newText = displayText + autocompleteText;
      setDisplayText(newText);
      onChange(transformText(newText));
      setAutocompleteText('');
    }
  };

  // Add random positive word every few seconds if they're typing
  useEffect(() => {
    if (displayText.length > 20 && displayText.length < 50) {
      const timer = setTimeout(() => {
        if (!displayText.endsWith(' ')) return;
        const randomWord = positiveWords[Math.floor(Math.random() * positiveWords.length)];
        if (!displayText.toLowerCase().includes(randomWord)) {
          setDisplayText(prev => prev + randomWord + ' ');
          onChange(transformText(displayText + randomWord + ' '));
        }
      }, 3000);
      return () => clearTimeout(timer);
    }
  }, [displayText]);

  return (
    <div className="text-feedback-container">
      <div className="text-feedback-question">
        {config.textFeedback.question}
      </div>

      <div className="textarea-wrapper">
        <textarea
          className="feedback-textarea"
          value={displayText}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
          placeholder={`Type your feedback about ${config.name} here... (it will be improved automatically)`}
          rows={4}
        />
        {autocompleteText && (
          <span className="autocomplete-hint">
            {displayText}<span className="suggestion">{autocompleteText}</span>
            <span className="tab-hint">(Tab to complete)</span>
          </span>
        )}
      </div>

      {value && value !== displayText && (
        <div className="transformed-preview">
          <span className="preview-label">✨ Enhanced feedback:</span>
          <p className="preview-text">{value}</p>
        </div>
      )}

      <div className="text-hint">
        Your feedback will be automatically enhanced for clarity
      </div>
    </div>
  );
};
